// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBESE_oBLKwYtHBqhto7r4_NmkI5O09ER4',
    appId: '1:553661602646:web:5e34c32c8f6dc2b10fd4f7',
    messagingSenderId: '553661602646',
    projectId: 'firebasetestsalah',
    authDomain: 'fir-testsalah.firebaseapp.com',
    storageBucket: 'firebasetestsalah.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7tRrgWt4J5xoueM10XNFymBvfTi3SXTc',
    appId: '1:553661602646:android:bb304ab380a0f24d0fd4f7',
    messagingSenderId: '553661602646',
    projectId: 'firebasetestsalah',
    storageBucket: 'firebasetestsalah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYpII4lnVVktjoz9H-fa3_QBNyl_WoMrM',
    appId: '1:553661602646:ios:b1360e2d394ab9db0fd4f7',
    messagingSenderId: '553661602646',
    projectId: 'firebasetestsalah',
    storageBucket: 'firebasetestsalah.appspot.com',
    iosClientId: '553661602646-tkmo7331f72ahcib96u5cr72m1qfe735.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYpII4lnVVktjoz9H-fa3_QBNyl_WoMrM',
    appId: '1:553661602646:ios:886b45439e0ec22d0fd4f7',
    messagingSenderId: '553661602646',
    projectId: 'firebasetestsalah',
    storageBucket: 'firebasetestsalah.appspot.com',
    iosClientId: '553661602646-kj73kbpuks46sp74v0dm5sa3t7uph6p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireChat.RunnerTests',
  );
}
